package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Oct 7, 2023, 10:27:50 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * Advertisement generated by hbm2java
 */
public class Advertisement implements java.io.Serializable {

	private Integer advertisementId;
	private Hotel hotel;
	private Date dateStart;
	private Date dateEnd;

	public Advertisement() {
	}

	public Advertisement(Hotel hotel, Date dateStart, Date dateEnd) {
		this.hotel = hotel;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
	}

	public Integer getAdvertisementId() {
		return this.advertisementId;
	}

	public void setAdvertisementId(Integer advertisementId) {
		this.advertisementId = advertisementId;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

}
