package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Oct 7, 2023, 10:27:50 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * District generated by hbm2java
 */
public class District implements java.io.Serializable {

	private Integer districtId;
	private Province province;
	private String name;
	@JsonIgnore
	private Set subdistricts = new HashSet(0);

	public District() {
	}

	public District(Province province, String name) {
		this.province = province;
		this.name = name;
	}

	public District(Province province, String name, Set subdistricts) {
		this.province = province;
		this.name = name;
		this.subdistricts = subdistricts;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getSubdistricts() {
		return this.subdistricts;
	}

	public void setSubdistricts(Set subdistricts) {
		this.subdistricts = subdistricts;
	}

}
