package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Nov 4, 2023, 2:14:42 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * District generated by hbm2java
 */
public class District implements java.io.Serializable {

	private Integer districtId;
	private Province province;
	private String name;
	@JsonIgnore
	private List<Subdistrict> subdistricts = new ArrayList<Subdistrict>();

	public District() {
	}

	public District(Province province, String name) {
		this.province = province;
		this.name = name;
	}

	public District(Province province, String name, List<Subdistrict> subdistricts) {
		this.province = province;
		this.name = name;
		this.subdistricts = subdistricts;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Subdistrict> getSubdistricts() {
		return this.subdistricts;
	}

	public void setSubdistricts(List<Subdistrict> subdistricts) {
		this.subdistricts = subdistricts;
	}

}
