package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Nov 5, 2023, 3:52:08 AM by Hibernate Tools 5.6.3.Final

/**
 * Facilities generated by hbm2java
 */
public class Facilities implements java.io.Serializable {

	private Integer facilitiesId;
	private Facilitiesname facilitiesname;
	private Hotel hotel;

	public Facilities() {
	}

	public Facilities(Facilitiesname facilitiesname, Hotel hotel) {
		this.facilitiesname = facilitiesname;
		this.hotel = hotel;
	}

	public Integer getFacilitiesId() {
		return this.facilitiesId;
	}

	public void setFacilitiesId(Integer facilitiesId) {
		this.facilitiesId = facilitiesId;
	}

	public Facilitiesname getFacilitiesname() {
		return this.facilitiesname;
	}

	public void setFacilitiesname(Facilitiesname facilitiesname) {
		this.facilitiesname = facilitiesname;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

}
