package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Oct 7, 2023, 10:27:50 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel implements java.io.Serializable {

	private Integer hotelId;
	private Subdistrict subdistrict;
	private String name;
	private String address;
	private Date openTime;
	private Date closeTime;
	private String status;
	private Date checkinTime;
	private boolean facilities;
	private Set advertisements = new HashSet(0);
	private Set rooms = new HashSet(0);
	private List<Imghotel> imghotels = new ArrayList<Imghotel>();

	public Hotel() {
	}

	public Hotel(Subdistrict subdistrict, String name, String address, Date openTime, Date closeTime, String status,
			Date checkinTime, boolean facilities) {
		this.subdistrict = subdistrict;
		this.name = name;
		this.address = address;
		this.openTime = openTime;
		this.closeTime = closeTime;
		this.status = status;
		this.checkinTime = checkinTime;
		this.facilities = facilities;
	}

	public Hotel(Subdistrict subdistrict, String name, String address, Date openTime, Date closeTime, String status,
			Date checkinTime, boolean facilities, Set advertisements, Set rooms, List<Imghotel> imghotels) {
		this.subdistrict = subdistrict;
		this.name = name;
		this.address = address;
		this.openTime = openTime;
		this.closeTime = closeTime;
		this.status = status;
		this.checkinTime = checkinTime;
		this.facilities = facilities;
		this.advertisements = advertisements;
		this.rooms = rooms;
		this.imghotels = imghotels;
	}

	public Integer getHotelId() {
		return this.hotelId;
	}

	public void setHotelId(Integer hotelId) {
		this.hotelId = hotelId;
	}

	public Subdistrict getSubdistrict() {
		return this.subdistrict;
	}

	public void setSubdistrict(Subdistrict subdistrict) {
		this.subdistrict = subdistrict;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	public Date getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCheckinTime() {
		return this.checkinTime;
	}

	public void setCheckinTime(Date checkinTime) {
		this.checkinTime = checkinTime;
	}

	public boolean isFacilities() {
		return this.facilities;
	}

	public void setFacilities(boolean facilities) {
		this.facilities = facilities;
	}

	public Set getAdvertisements() {
		return this.advertisements;
	}

	public void setAdvertisements(Set advertisements) {
		this.advertisements = advertisements;
	}

	public Set getRooms() {
		return this.rooms;
	}

	public void setRooms(Set rooms) {
		this.rooms = rooms;
	}

	public List<Imghotel> getImghotels() {
		return this.imghotels;
	}

	public void setImghotels(List<Imghotel> imghotels) {
		this.imghotels = imghotels;
	}

}
