package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Nov 4, 2023, 2:14:42 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Hotel generated by hbm2java
 */
public class Hotel implements java.io.Serializable {

	private Integer hotelId;
	private Subdistrict subdistrict;
	private String name;
	private String address;
	private Date openTime;
	private Date closeTime;
	private String status;
	private Date checkinTime;
	private String privateKey;
	@JsonIgnore
	private List<Advertisement> advertisements = new ArrayList<Advertisement>();
	@JsonIgnore
	private List<Userhotel> userhotels = new ArrayList<Userhotel>();
	@JsonIgnore
	private List<Room> rooms = new ArrayList<Room>();
	@JsonIgnore
	private List<Facilities> facilitieses = new ArrayList<Facilities>();
	@JsonIgnore
	private List<Imghotel> imghotels = new ArrayList<Imghotel>();

	public Hotel() {
	}

	public Hotel(Subdistrict subdistrict, String name, String address, Date openTime, Date closeTime, String status,
			Date checkinTime, String privateKey) {
		this.subdistrict = subdistrict;
		this.name = name;
		this.address = address;
		this.openTime = openTime;
		this.closeTime = closeTime;
		this.status = status;
		this.checkinTime = checkinTime;
		this.privateKey = privateKey;
	}

	public Hotel(Subdistrict subdistrict, String name, String address, Date openTime, Date closeTime, String status,
			Date checkinTime, String privateKey, List<Advertisement> advertisements, List<Userhotel> userhotels, List<Room> rooms,
			List<Facilities> facilitieses, List<Imghotel> imghotels) {
		this.subdistrict = subdistrict;
		this.name = name;
		this.address = address;
		this.openTime = openTime;
		this.closeTime = closeTime;
		this.status = status;
		this.checkinTime = checkinTime;
		this.privateKey = privateKey;
		this.advertisements = advertisements;
		this.userhotels = userhotels;
		this.rooms = rooms;
		this.facilitieses = facilitieses;
		this.imghotels = imghotels;
	}

	public Integer getHotelId() {
		return this.hotelId;
	}

	public void setHotelId(Integer hotelId) {
		this.hotelId = hotelId;
	}

	public Subdistrict getSubdistrict() {
		return this.subdistrict;
	}

	public void setSubdistrict(Subdistrict subdistrict) {
		this.subdistrict = subdistrict;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	public Date getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCheckinTime() {
		return this.checkinTime;
	}

	public void setCheckinTime(Date checkinTime) {
		this.checkinTime = checkinTime;
	}

	public String getPrivateKey() {
		return this.privateKey;
	}

	public void setPrivateKey(String privateKey) {
		this.privateKey = privateKey;
	}

	public List<Advertisement> getAdvertisements() {
		return this.advertisements;
	}

	public void setAdvertisements(List<Advertisement> advertisements) {
		this.advertisements = advertisements;
	}

	public List<Userhotel> getUserhotels() {
		return this.userhotels;
	}

	public void setUserhotels(List<Userhotel> userhotels) {
		this.userhotels = userhotels;
	}

	public List<Room> getRooms() {
		return this.rooms;
	}

	public void setRooms(List<Room> rooms) {
		this.rooms = rooms;
	}

	public List<Imghotel> getImghotels() {
		return this.imghotels;
	}

	public void setImghotels(List<Imghotel> imghotels) {
		this.imghotels = imghotels;
	}

	public List<Facilities> getFacilitieses() {
		return facilitieses;
	}

	public void setFacilitieses(List<Facilities> facilitieses) {
		this.facilitieses = facilitieses;
	} 

}
