package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Nov 4, 2023, 2:14:42 PM by Hibernate Tools 5.6.3.Final

/**
 * Imghotel generated by hbm2java
 */
public class Imghotel implements java.io.Serializable {

	private Integer imghotelId;
	private Hotel hotel;
	private String filePath;

	public Imghotel() {
	}

	public Imghotel(Hotel hotel, String filePath) {
		this.hotel = hotel;
		this.filePath = filePath;
	}

	public Integer getImghotelId() {
		return this.imghotelId;
	}

	public void setImghotelId(Integer imghotelId) {
		this.imghotelId = imghotelId;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
