package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Nov 4, 2023, 2:14:42 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private Integer provinceId;
	private String name;
	@JsonIgnore
	private List<District> districts = new ArrayList<District>();

	public Province() {
	}

	public Province(String name) {
		this.name = name;
	}

	public Province(String name, List<District> districts) {
		this.name = name;
		this.districts = districts;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(List<District> districts) {
		this.districts = districts;
	}

}
