package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Oct 7, 2023, 10:27:50 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private Integer provinceId;
	private String name;
	@JsonIgnore
	private Set districts = new HashSet(0);

	public Province() {
	}

	public Province(String name) {
		this.name = name;
	}

	public Province(String name, Set districts) {
		this.name = name;
		this.districts = districts;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set districts) {
		this.districts = districts;
	}

}
