package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Nov 4, 2023, 2:14:42 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Room generated by hbm2java
 */
public class Room implements java.io.Serializable {

	private Integer roomId;
	@JsonIgnore
	private Hotel hotel;
	private int guest;
	private String type;
	private int price;
	private int amountRoom;
	@JsonIgnore
	private List<Reservation> reservations = new ArrayList<Reservation>();

	public Room() {
	}

	public Room(Hotel hotel, int guest, String type, int price, int amountRoom) {
		this.hotel = hotel;
		this.guest = guest;
		this.type = type;
		this.price = price;
		this.amountRoom = amountRoom;
	}

	public Room(Hotel hotel, int guest, String type, int price, int amountRoom, List<Reservation> reservations) {
		this.hotel = hotel;
		this.guest = guest;
		this.type = type;
		this.price = price;
		this.amountRoom = amountRoom;
		this.reservations = reservations;
	}

	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public int getGuest() {
		return this.guest;
	}

	public void setGuest(int guest) {
		this.guest = guest;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getAmountRoom() {
		return this.amountRoom;
	}

	public void setAmountRoom(int amountRoom) {
		this.amountRoom = amountRoom;
	}

	public List<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(List<Reservation> reservations) {
		this.reservations = reservations;
	}

}
