package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Oct 7, 2023, 10:27:50 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Subdistrict generated by hbm2java
 */
public class Subdistrict implements java.io.Serializable {

	private Integer subdistrictId;
	private District district;
	private String name;
	private Set vacations = new HashSet(0);
	private Set hotels = new HashSet(0);

	public Subdistrict() {
	}

	public Subdistrict(District district, String name) {
		this.district = district;
		this.name = name;
	}

	public Subdistrict(District district, String name, Set vacations, Set hotels) {
		this.district = district;
		this.name = name;
		this.vacations = vacations;
		this.hotels = hotels;
	}

	public Integer getSubdistrictId() {
		return this.subdistrictId;
	}

	public void setSubdistrictId(Integer subdistrictId) {
		this.subdistrictId = subdistrictId;
	}

	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getVacations() {
		return this.vacations;
	}

	public void setVacations(Set vacations) {
		this.vacations = vacations;
	}

	public Set getHotels() {
		return this.hotels;
	}

	public void setHotels(Set hotels) {
		this.hotels = hotels;
	}

}
