package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Oct 7, 2023, 10:27:50 PM by Hibernate Tools 5.6.3.Final

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private Integer tagId;
	private Tagname tagname;
	private Vacation vacation;

	public Tag() {
	}

	public Tag(Tagname tagname, Vacation vacation) {
		this.tagname = tagname;
		this.vacation = vacation;
	}

	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public Tagname getTagname() {
		return this.tagname;
	}

	public void setTagname(Tagname tagname) {
		this.tagname = tagname;
	}

	public Vacation getVacation() {
		return this.vacation;
	}

	public void setVacation(Vacation vacation) {
		this.vacation = vacation;
	}

}
