package th.ac.ku.kps.eng.cpe.ds.project.model;
// Generated Nov 4, 2023, 2:14:42 PM by Hibernate Tools 5.6.3.Final

/**
 * Userhotel generated by hbm2java
 */
public class Userhotel implements java.io.Serializable {

	private Integer userHotelId;
	private Hotel hotel;
	private User user;

	public Userhotel() {
	}

	public Userhotel(Hotel hotel, User user) {
		this.hotel = hotel;
		this.user = user;
	}

	public Integer getUserHotelId() {
		return this.userHotelId;
	}

	public void setUserHotelId(Integer userHotelId) {
		this.userHotelId = userHotelId;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
